### ISSUE TITLE
some code is missing

### ISSUE THREAD

**Issue by tujie3** [katarinastuart/Sv5_StarlingWGS#1]
![image](https://user-images.githubusercontent.com/75846117/227747092-1a41d5e1-7738-409e-91c3-89eea2c16ed9.png)
As you see, is some code missing here? And  how was the file 'survivor_unsorted.vcf ' generated ? I hope you can provide the missing part, thanks!

**Comment by katarinastuart** [comment]
Apologies, this seems to have been cut off during PDF generation! The missing line of code is supposed to combine the three separate SURVIVOR merged VCF files (one file for each potential genotype: 0/0 or homref, 0/1 or het, and 1/1/ or homalt) into one VCF file. Once we have done this we then use BCFTOOLs to perform the sort action so they are ordered based on their genomic positioning. So the missing line is:

`cat ${SAMPLE}_survivor_header ${SAMPLE}_survivor_homref_SNPs.vcf  ${SAMPLE}_survivor_het_SNPs.vcf  ${SAMPLE}_survivor_homalt_SNPs.vcf > ${SAMPLE}_survivor_unsorted.vcf`

One thing to note here is that it is very important that you only use this approach (splitting by genotype then merging) if the SURVIVOR caller consensus is set to a majority. So for instance, if you used three separate SV callers and merge if there is consensus in 2/3 of the programs, this is a majority. Same for if you use five programs, and merge if there is consensus for 3/5, or 4/5 of them. But if, for example, you use four programs and set the consensus to 2/4, then you could end up with the same SV being merged back into your final VCF data set twice (if it was called as heterozygous by two callers, and homozygous ref by two callers, but all other parameters fit the rest of you merge criteria).

**Comment by tujie3** [comment]
Thanks, it is definitely helpful to me
